### ISSUE TITLE
deploying bionic ussuri uses latest/stable for some charms

### ISSUE THREAD

**Issue by dosaboy** [canonical/stsstack-bundles#131]
While this used to be valid it is no longer since that channel has been updated to be more recent version that does not support bionic.

**Comment by lathiat** [comment]
rabbitmq is one of those charms with some jacked up release info in `juju info rabbitmq-server --format json | jq`

3.6/edge r123 supports 16.04, 18.04, 20.04, 20.10, 21.04, 21.10
3.6/edge r133 supports 16.04, 18.04
3.6/edge r135 supports 16.04, 20.04

and there is no 3.6/stable

so 3.6/edge might work
otherwise 3.8/stable probably also will



ovn also needs to be set to 20.03

**Comment by nicolasbock** [comment]
Closing since fixed in #132
