### ISSUE TITLE
Provider 'ovn' is not enabled after deploying openstack with --octavia-ovn-provider

### ISSUE THREAD

**Issue by marino-mrc** [canonical/stsstack-bundles#22]
Hello,
I deployed the environment with 

./generate-bundle.sh --octavia-ovn-provider --ovn -s focal -r ussuri --charmstore -n mymodel

then
./tools/vault-unseal-and-authorise.sh
./tools/configure_octavia.sh

./configure
source novarc
./tools/sec_groups

when I try to create a new load balancer using the 'ovn' provider I have the following error:
`
openstack loadbalancer create --vip-network-id private --provider ovn --name lb1
Provider 'ovn' is not enabled. (HTTP 400) (Request-ID: req-970b3275-42b1-4b78-878b-37d2577e3222)

`

Checking the YAML files, I noticed the octavia-ovn-provider.yaml file but it adds a relation between octavia:ovsdb-cms, ovn-central:ovsdb-cms and nothing else. 
So it seems that some required packages and configuration parameters are actually missing.

Thank you.
Regards,
Marco

**Comment by sombrafam** [comment]
Hi Marino,

Thanks for creating this bug. The '--octavia-ovn-provider' was the default provider when OVN was enabled but it was disabled by default exactly because it wasn't supported or didn't work (or both) in all releases. So, I think that Ussuri is one of those.
If this is is an Octavia or OVN limitation for Ussuri, we should document in the charm CLI. If this is a bundle limitation we should  fix it.

 Are you troubleshooting or reproducing something that is happening with the OVN provider in the ussuri release?

Erlon

**Comment by dosaboy** [comment]
Looks like we are missing enable-amphora=False [1]

[1] https://opendev.org/openstack/charm-octavia/#ovn-provider
