### ISSUE TITLE
The default 80Gb for nova-compute's vda is a bit big

### ISSUE THREAD

**Issue by lccnblack** [canonical/stsstack-bundles#229]
The default size of vda as root disk is 80Gb, and it seems that we can change it by adjusting the parameter MOD_PARAMS[__NOVA_COMPUTE_UNIT_CONSTRAINTS __] (/stsstack-bundles/openstack/pipeline/02configure)to change the size 

The default vda is 30GB for normal nodes, suppose an OpenStack without HA, with ceph, Octavia and 2 nova-compute, 
Then the vda alone occupies no less than 600GB（20*30Gb), if we add 2*50Gb vdb, then it is very easy to meet the upper limit of 1000GB. 
for example
` ./generate-bundle.sh --no-ml2dns --vault --ceph --octavia --num-compute 2 --series focal
`

And in addition to having an OpenStack environment, we usually have other test environments in parallel.

And vdb already has 50Gb(/stsstack-bundles/openstack/b/o/openstack/vault-openstack-secrets.yaml) as an ephemeral disk directory (/var/lib/nova/instances), so why does vda need to have 80Gb of space?
BTW, 50Gb for nova-compute vdb, is it also too big?

I think 30Gb is more reasonable for root disk of nova-compute.

**Comment by lathiat** [comment]
I independently came to the same conclusion, then found this existing bug, thanks @lccnblack 

The reason the vault overlay has a separate ephemeral disk is to exercise disk-encryption with vault. This made sense when vault wasn't the default, but since we added OVN (a long time ago now) this always gets pulled in by default.

I think a simple fix here is to revert nova-compute back to a 30G default root-disk, and always enable the 50G ephemeral disk even without vault.

I'm just testing the practical effect of this before I'll raise a PR to that effect. Double checking what storage does or doesn't get written to the ephemeral disk and whether the over-subscribed disk quota is effected by the root disk or not.
