### ISSUE TITLE
OpenStack VMs loose network access when computes are restarted

### ISSUE THREAD

**Issue by sombrafam** [canonical/stsstack-bundles#47]
STSStack deployments loose connectivity to the deployment instances
    if the deployment is shutoff. This happens because the interfaces are
    renamed after boot and OVS DB entries doesn't match with the new
    interface names. To fix that we need to make the interface names
    persistent.

**Comment by sombrafam** [comment]
Any deployment with DVR or l3ha for sure. Not sure about the ones with OVN

**Comment by sombrafam** [comment]
No, its not an OpenStack issue. Its related to the way the OpenStack instances are created and stsstack add the interfaces to neutron gateways and computes. That use to be done by a script named add-data-ports.sh.


This was the fix I was trying. But I think this is now done somewhere else.

```patch
diff --git a/openstack/bin/add-data-ports.sh b/openstack/bin/add-data-ports.sh
index 6df560d..826dcc6 100755
--- a/openstack/bin/add-data-ports.sh
+++ b/openstack/bin/add-data-ports.sh
@@ -29,6 +29,7 @@ openstack port list --long --format json \
 [ -n "$network" ] || network="${OS_PROJECT_NAME}_admin_net"
 
 readarray -t instances<<<"`juju status $application --format=json| jq -r '.machines[].\"instance-id\"'`"
+readarray -t hosts<<<"`juju status $application --format=json| jq -r '.machines[].\"hostname\"'`"
 
 if [ "$application" = "ovn-chassis" ] && \
         ((`juju status ovn-chassis --format=json 2>/dev/null| jq '.machines| length'`)); then
@@ -80,11 +81,19 @@ if ((require_count)); then
     declare -a mac_addrs=()
     i=0
     for inst in "${instances[@]}"; do
+        hostname=${hosts[${i}]}
         ${requires[$inst]} || continue
         port=${ports_filtered[$((i++))]}
         echo "Adding port $port to server $inst"
         openstack server add port $inst $port
-        mac_addrs+=( "`openstack port show -c mac_address -f value $port`" )
+        mac_addr=`openstack port show -c mac_address -f value $port`
+        # ifname=`juju ssh ${hostname} 'find /sys/class/net -mindepth 1 -maxdepth 1 ! -name lo -printf "%P: " -execdir cat {}/address \; | grep '${mac_addr}'|cut -d: -f1'`
+        tmp_yaml=`mktemp`
+        cp ./templates/99-stsstack-networks.yaml ${tmp_yaml}
+        sed -i "s/__MACADDR__/${mac_addr}/g" ${tmp_yaml}
+        juju scp $tmp_yaml $hostname:~/99-stsstack-networks.yaml
+        juju ssh $hostname 'sudo mv ~/99-stsstack-networks.yaml /etc/netplan/ && sudo netplan apply'
+        mac_addrs+=( "${mac_addr}" )
     done
     echo "Updating $application $optname"
     cfg="`juju config $application $optname`"
diff --git a/openstack/templates/99-stsstack-networks.yaml b/openstack/templates/99-stsstack-networks.yaml
new file mode 100644
index 0000000..89c446b
--- /dev/null
+++ b/openstack/templates/99-stsstack-networks.yaml
@@ -0,0 +1,9 @@
+network:
+    version: 2
+    ethernets:
+        ens4:
+            dhcp4: false
+            match:
+                macaddress: __MACADDR__
+            mtu: 8958
+            set-name: ens4

```

**Comment by lathiat** [comment]
The interface changes name on reboot because a hot-attached network device versus cold-attached gets a different PCI device slot. So it switches from ens7 after hot-add to ens4 on cold-boot. However the charm start hook, should, fix this on boot.

There are a couple bugs about this but I can't find the one that explains it best to do with libvirt and pcie hotplug:
https://bugs.launchpad.net/nova/+bug/1696664

Seems cloud-init has no support for interface 'tags' which were implemented in 2017. But I may be wrong:
https://specs.openstack.org/openstack/nova-specs/specs/mitaka/approved/virt-device-role-tagging.html


However per the above comment the bigger issue is that the interface never is set "up" (ip link set ens4 up). At one point the charm also used to do this but it was removed. The extra netplan file is a workable fix. I am wondering how we can do this is a more generic way than juju ssh. for example we could set model-wide userdata for cloud-init to do something with this interface but I am not sure how we can give it a persistent name without matching on the MAC address which we don't know until later. The only other option that comes to mind is trying to add the interface as soon as possible and then cloud-init may write it into the netplan file? 

Or otherwise we could enhance the charm to handle this case somehow.

**Comment by sombrafam** [comment]
Em qui., 30 de jun. de 2022 às 23:07, Trent Lloyd ***@***.***>
escreveu:

> The interface changes name on reboot because a hot-attached network device
> versus cold-attached gets a different PCI device slot. So it switches from
> ens7 after hot-add to ens4 on cold-boot. However the charm start hook,
> should, fix this on boot.
>
I dont think the charm hook should fix this. Not unless you set a config to
map the new name to the bridge mapping. By the way, I looked on the export
bundles, and I don't see anywhere there where this is set.
That is currently being configured later using the script I mentioned or
the other method. So, I think that it might be possible to add both devices
ens4 and ens7 in the bridge mappings configuration and get
it working for both scenarios?


> There are a couple bugs about this but I can't find the one that explains
> it best to do with libvirt and pcie hotplug:
> https://bugs.launchpad.net/nova/+bug/1696664
>
> Seems cloud-init has no support for interface 'tags' which were
> implemented in 2017. But I may be wrong:
>
> https://specs.openstack.org/openstack/nova-specs/specs/mitaka/approved/virt-device-role-tagging.html
>
> However per the above comment the bigger issue is that the interface never
> is set "up" (ip link set ens4 up). At one point the charm also used to do
> this but it was removed. The extra netplan file is a workable fix. I am
> wondering how we can do this is a more generic way than juju ssh. for
> example we could set model-wide userdata for cloud-init to do something
> with this interface but I am not sure how we can give it a persistent name
> without matching on the MAC address which we don't know until later. The
> only other option that comes to mind is trying to add the interface as soon
> as possible and then cloud-init may write it into the netplan file?
>
> Or otherwise we could enhance the charm to handle this case somehow.
>
So, the charm doesn't have any bridge/mapping config. May be setting
data-port="br-data:ens4 br-data:ens7" would fix?

**Comment by lathiat** [comment]
The charm sets data-port with a list of MAC addresses after adding the ports - which is why the charm hook can fix it if config-changed runs as it looks for the MAC address again and finds the new interface name.

However I think they maybe dropped config-changed running on reboot also so maybe that doesn't happen now either. Would have to quickly check.

**Comment by sombrafam** [comment]
So, I tried to set `data-port="br-data:ens4 br-data:ens7"` and the environment works after the reboot. We just need to know if there would be any side effects for using the interface name instead of MAC address.

Changing the charm behavior seems a bit to complicated and this use case doesn't seem to pay off the regression possibility.

**Comment by dosaboy** [comment]
@sombrafam to fix after reboot you just need to run the config-changed hook e.g.

```
juju run -a neutron-openvswitch -- hooks/config-changed
```

or


```
juju run -a ovn-chassis -- hooks/config-changed
```

**Comment by sombrafam** [comment]
I'll try that one later. But it would be nice to have a way to get it
working out of the box. Im sure this is an obscure hack that most people
wont know.

Em seg., 4 de jul. de 2022 às 15:51, Edward Hope-Morley <
***@***.***> escreveu:

**Comment by dosaboy** [comment]
The problem is that you can't know 100% what the interface names will be when the machine boots. In fact that is the problem you are facing because the first time it boot its ens4 then after reboot its ens7 and if you add more interfaces and reboot it might change again. This is why we use mac addresses and in real deployments the interface names are persistent because maas/juju set them in netplan. If you really wanted to do this with the Openstack provider you could maybe consider configdrive but i just don't think it is worth the effort when you could just run the config-changed hook. And for what its worth, after the first reboot it is unlikely that the interface name will change again if you don't add more interfaces so this is really something you would need to do once per model/deployment.

**Comment by sombrafam** [comment]
I run the config-changed action and it worked. Given that we have that option and fixing this behavior seems unpractical. I'll close this issue.
